# Generated by Django 5.0.6 on 2024-05-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_intent", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("plan", models.JSONField(blank=True)),
                ("guidance", models.TextField(blank=True)),
                ("intro", models.TextField(blank=True)),
                ("outro", models.TextField(blank=True)),
                ("paragraphs", models.JSONField(blank=True)),
                ("stable_prompt", models.TextField(blank=True)),
                ("img_title", models.CharField(blank=True, max_length=255)),
                ("jpg_name", models.CharField(blank=True, max_length=255)),
                ("img_alt", models.CharField(blank=True, max_length=255)),
                ("nearest_title", models.CharField(blank=True, max_length=255)),
                ("nearest_title_CTA", models.CharField(blank=True, max_length=255)),
                ("backlink_slug", models.CharField(blank=True, max_length=255)),
                ("book_title", models.CharField(blank=True, max_length=255)),
                ("book_CTA", models.CharField(blank=True, max_length=255)),
                ("book_link", models.URLField(blank=True)),
                ("book_description", models.TextField(blank=True)),
                ("bold_list", models.JSONField(blank=True)),
                ("yt_id", models.CharField(blank=True, max_length=255)),
                ("yt_title", models.CharField(blank=True, max_length=255)),
                ("yt_url", models.URLField(blank=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
